{% set name = "wxmplot" %}
{% set version = "2026.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fcf51c264460413ee3084349c4514738408390f6a9bc98dadb991dc9e3d8b182

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation

requirements:
  host:
    - python >={{ python_min }}
    - pip
    - setuptools >=45
    - wheel
    - setuptools_scm >=6.2
  run:
    - python >={{ python_min }}
    - setuptools
    - setuptools-scm
    - matplotlib-base >=3.10
    - pytz >=2025.2
    - numpy >=2
    - pyyaml >=5.0
    - darkdetect
    - wxpython >=4.2.2
    - wxutils >=2026.1.0
    - pyshortcuts >=1.9.5
    - Pillow >=7.0

test:
  imports:
    - wxmplot

about:
  home: https://newville.github.io/wxmplot
  license: MIT
  license_file: LICENSE
  summary: wxPython plotting widgets using matplotlib
  doc_url: https://newville.github.io/wxmplot
  dev_url: https://github.com/newville/wxmplot

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - newville
    - maurov
    - conda-forge/event-model
