{% set name = "wxmplot" %}
{% set version = "0.9.49" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 354001a94bce75eb42b7e96b627044f02be6d709bcc142196c5cba698f23fb95

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - matplotlib-base >=2.0
    - numpy >=1.12
    - six >=1.10
    - wxpython >=4.0.3
    - wxutils

test:
  imports:
    - wxmplot

about:
  home: http://newville.github.io/wxmplot
  license: MIT
  license_file: LICENSE
  summary: wxPython plotting widgets using matplotlib
  doc_url: http://newville.github.io/wxmplot
  dev_url: https://github.com/newville/wxmplot

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
