{% set name = "wxmplot" %}
{% set version = "2026.2.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 303f8cb15589146641e464793c051bd348822ffc26ba6cf37a03d9d8b832081e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation

requirements:
  host:
    - python >={{ python_min }}
    - pip
    - setuptools >=45
    - wheel
    - setuptools_scm >=6.2
  run:
    - python >={{ python_min }}
    - setuptools
    - setuptools-scm
    - matplotlib-base >=3.10
    - pytz >=2025.2
    - numpy >=2
    - pyyaml >=5.0
    - darkdetect
    - wxpython >=4.2.3
    - wxutils >=2026.3.0
    - pyshortcuts >=1.9.8
    - Pillow >=7.0

test:
  imports:
    - wxmplot

about:
  home: https://newville.github.io/wxmplot
  license: MIT
  license_file: LICENSE
  summary: wxPython plotting widgets using matplotlib
  doc_url: https://newville.github.io/wxmplot
  dev_url: https://github.com/newville/wxmplot

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - newville
    - maurov
    - conda-forge/event-model
