{% set name = "wxmplot" %}
{% set version = "0.9.59" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f638aa9d005ece0916f60ff1a28532689c4a0f88f9245079fda5cdba54215bd

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=45
    - wheel
    - setuptools_scm >=6.2
  run:
    - python >=3.6
    - matplotlib-base >=2.0
    - numpy >=1.12
    - pyyaml
    - six >=1.10
    - wxpython >=4.0.3
    - wxutils

test:
  imports:
    - wxmplot

about:
  home: http://newville.github.io/wxmplot
  license: MIT
  license_file: LICENSE
  summary: wxPython plotting widgets using matplotlib
  doc_url: http://newville.github.io/wxmplot
  dev_url: https://github.com/newville/wxmplot

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
