{% set name = "wxmplot" %}
{% set version = "2025.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a31a9a28ff94e83264f41f38b12e85cbf2b552ea7feecf0432e1b64a8a25acb6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - matplotlib-base >=2.0
    - numpy >=1.12
    - pyyaml
    - six >=1.10
    - wxpython >=4.0.3
    - wxutils

test:
  imports:
    - wxmplot

about:
  home: http://newville.github.io/wxmplot
  license: MIT
  license_file: LICENSE
  summary: wxPython plotting widgets using matplotlib
  doc_url: http://newville.github.io/wxmplot
  dev_url: https://github.com/newville/wxmplot

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
