	{% set name = "wxmplot" %}
	{% set version = "2025.1.6" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 43846b3d5e74661cbecd1847e93e4e188ce29c53d4ca570e9cf8c7cb8b57dd20

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >={{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - setuptools
    - setuptools-scm
    - matplotlib-base >=3.9
    - pytz
    - numpy >=1.26
    - pyyaml >=5.0
    - darkdetect
    - wxpython >=4.2.0
    - wxutils >=0.3.3
    - pyshortcuts >=1.9.5
    - Pillow >=7.0

test:
  imports:
    - wxmplot

about:
  home: https://newville.github.io/wxmplot
  license: MIT
  license_file: LICENSE
  summary: wxPython plotting widgets using matplotlib
  doc_url: https://newville.github.io/wxmplot
  dev_url: https://github.com/newville/wxmplot

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - newville
    - conda-forge/event-model
